# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'piDisplayGUI.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 480)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.BlankCursor))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMaximumSize(QtCore.QSize(790, 470))
        self.centralwidget.setCursor(QtGui.QCursor(QtCore.Qt.BlankCursor))
        self.centralwidget.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.centralwidget.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.Sweden))
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 561, 331))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_main = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_main.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_main.setObjectName("gridLayout_main")
        self.line = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line.setCursor(QtGui.QCursor(QtCore.Qt.BlankCursor))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_main.addWidget(self.line, 1, 1, 1, 1)
        self.lcdNumber = QtWidgets.QLCDNumber(self.gridLayoutWidget)
        self.lcdNumber.setCursor(QtGui.QCursor(QtCore.Qt.BlankCursor))
        self.lcdNumber.setObjectName("lcdNumber")
        self.gridLayout_main.addWidget(self.lcdNumber, 0, 0, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_2.setCursor(QtGui.QCursor(QtCore.Qt.BlankCursor))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_main.addWidget(self.line_2, 1, 0, 1, 1)
        self.horizontalLayout_top_right = QtWidgets.QHBoxLayout()
        self.horizontalLayout_top_right.setObjectName("horizontalLayout_top_right")
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setStyleSheet("font: 18pt \"Myanmar Text\";")
        self.label.setObjectName("label")
        self.horizontalLayout_top_right.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setStyleSheet("font: 18pt \"Myanmar Text\";")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_top_right.addWidget(self.label_2)
        self.gridLayout_main.addLayout(self.horizontalLayout_top_right, 0, 1, 1, 1)
        self.tabWidget_bottom_left = QtWidgets.QTabWidget(self.gridLayoutWidget)
        self.tabWidget_bottom_left.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.tabWidget_bottom_left.setObjectName("tabWidget_bottom_left")
        self.tab = QtWidgets.QWidget()
        self.tab.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.tab.setObjectName("tab")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.tab)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(2, 6, 311, 191))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_16 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName("label_16")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.label_17 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_17.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_17.setObjectName("label_17")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_17)
        self.temperatureLabel_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.temperatureLabel_2.setText("")
        self.temperatureLabel_2.setObjectName("temperatureLabel_2")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.temperatureLabel_2)
        self.label_18 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_18.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_18.setObjectName("label_18")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_18)
        self.humidityLabel_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.humidityLabel_2.setText("")
        self.humidityLabel_2.setObjectName("humidityLabel_2")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.humidityLabel_2)
        self.label_19 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_19.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_19.setObjectName("label_19")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_19)
        self.pressureLabel_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.pressureLabel_2.setText("")
        self.pressureLabel_2.setObjectName("pressureLabel_2")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.pressureLabel_2)
        self.label_20 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_20.setObjectName("label_20")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_20)
        self.label_21 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_21.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_21.setObjectName("label_21")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_21)
        self.longitudeLabel_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.longitudeLabel_2.setText("")
        self.longitudeLabel_2.setObjectName("longitudeLabel_2")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.longitudeLabel_2)
        self.label_22 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_22.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_22.setObjectName("label_22")
        self.formLayout_2.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_22)
        self.latitudeLabel_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.latitudeLabel_2.setText("")
        self.latitudeLabel_2.setObjectName("latitudeLabel_2")
        self.formLayout_2.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.latitudeLabel_2)
        self.label_23 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_23.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_23.setObjectName("label_23")
        self.formLayout_2.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_23)
        self.sunriseLabel_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.sunriseLabel_2.setText("")
        self.sunriseLabel_2.setObjectName("sunriseLabel_2")
        self.formLayout_2.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.sunriseLabel_2)
        self.label_24 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_24.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_24.setObjectName("label_24")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_24)
        self.label_25 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_25.setFont(font)
        self.label_25.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_25.setObjectName("label_25")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_25)
        self.windLabel_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.windLabel_2.setText("")
        self.windLabel_2.setObjectName("windLabel_2")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.windLabel_2)
        self.l_wind_result = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.l_wind_result.setText("")
        self.l_wind_result.setObjectName("l_wind_result")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.l_wind_result)
        self.label_27 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_27.setText("")
        self.label_27.setObjectName("label_27")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.label_27)
        self.label_28 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_28.setText("")
        self.label_28.setObjectName("label_28")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.label_28)
        self.verticalLayout.addLayout(self.formLayout_2)
        self.tabWidget_bottom_left.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.tab_2)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(0, 0, 321, 221))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.widget_plotRandom = QtWidgets.QWidget(self.verticalLayoutWidget_3)
        self.widget_plotRandom.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.widget_plotRandom.setObjectName("widget_plotRandom")
        self.layoutWidget_2 = QtWidgets.QWidget(self.widget_plotRandom)
        self.layoutWidget_2.setGeometry(QtCore.QRect(0, 90, 310, 98))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.forecastIcon4 = QtWidgets.QLabel(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.forecastIcon4.sizePolicy().hasHeightForWidth())
        self.forecastIcon4.setSizePolicy(sizePolicy)
        self.forecastIcon4.setMinimumSize(QtCore.QSize(16, 16))
        self.forecastIcon4.setMaximumSize(QtCore.QSize(200, 16))
        self.forecastIcon4.setBaseSize(QtCore.QSize(0, 0))
        self.forecastIcon4.setText("")
        self.forecastIcon4.setAlignment(QtCore.Qt.AlignCenter)
        self.forecastIcon4.setObjectName("forecastIcon4")
        self.gridLayout_2.addWidget(self.forecastIcon4, 1, 3, 1, 1)
        self.forecastTemp2 = QtWidgets.QLabel(self.layoutWidget_2)
        self.forecastTemp2.setText("")
        self.forecastTemp2.setObjectName("forecastTemp2")
        self.gridLayout_2.addWidget(self.forecastTemp2, 2, 1, 1, 1)
        self.forecastTemp5 = QtWidgets.QLabel(self.layoutWidget_2)
        self.forecastTemp5.setText("")
        self.forecastTemp5.setObjectName("forecastTemp5")
        self.gridLayout_2.addWidget(self.forecastTemp5, 2, 4, 1, 1)
        self.forecastTemp4 = QtWidgets.QLabel(self.layoutWidget_2)
        self.forecastTemp4.setText("")
        self.forecastTemp4.setObjectName("forecastTemp4")
        self.gridLayout_2.addWidget(self.forecastTemp4, 2, 3, 1, 1)
        self.forecastIcon2 = QtWidgets.QLabel(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.forecastIcon2.sizePolicy().hasHeightForWidth())
        self.forecastIcon2.setSizePolicy(sizePolicy)
        self.forecastIcon2.setMinimumSize(QtCore.QSize(16, 16))
        self.forecastIcon2.setMaximumSize(QtCore.QSize(200, 16))
        self.forecastIcon2.setBaseSize(QtCore.QSize(0, 0))
        self.forecastIcon2.setText("")
        self.forecastIcon2.setAlignment(QtCore.Qt.AlignCenter)
        self.forecastIcon2.setObjectName("forecastIcon2")
        self.gridLayout_2.addWidget(self.forecastIcon2, 1, 1, 1, 1)
        self.forecastIcon5 = QtWidgets.QLabel(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.forecastIcon5.sizePolicy().hasHeightForWidth())
        self.forecastIcon5.setSizePolicy(sizePolicy)
        self.forecastIcon5.setMinimumSize(QtCore.QSize(16, 16))
        self.forecastIcon5.setMaximumSize(QtCore.QSize(200, 16))
        self.forecastIcon5.setBaseSize(QtCore.QSize(0, 0))
        self.forecastIcon5.setText("")
        self.forecastIcon5.setAlignment(QtCore.Qt.AlignCenter)
        self.forecastIcon5.setObjectName("forecastIcon5")
        self.gridLayout_2.addWidget(self.forecastIcon5, 1, 4, 1, 1)
        self.forecastIcon1 = QtWidgets.QLabel(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.forecastIcon1.sizePolicy().hasHeightForWidth())
        self.forecastIcon1.setSizePolicy(sizePolicy)
        self.forecastIcon1.setMinimumSize(QtCore.QSize(16, 16))
        self.forecastIcon1.setMaximumSize(QtCore.QSize(200, 16))
        self.forecastIcon1.setBaseSize(QtCore.QSize(0, 0))
        self.forecastIcon1.setText("")
        self.forecastIcon1.setAlignment(QtCore.Qt.AlignCenter)
        self.forecastIcon1.setObjectName("forecastIcon1")
        self.gridLayout_2.addWidget(self.forecastIcon1, 1, 0, 1, 1)
        self.forecastIcon3 = QtWidgets.QLabel(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.forecastIcon3.sizePolicy().hasHeightForWidth())
        self.forecastIcon3.setSizePolicy(sizePolicy)
        self.forecastIcon3.setMinimumSize(QtCore.QSize(16, 16))
        self.forecastIcon3.setMaximumSize(QtCore.QSize(200, 16))
        self.forecastIcon3.setBaseSize(QtCore.QSize(0, 0))
        self.forecastIcon3.setText("")
        self.forecastIcon3.setAlignment(QtCore.Qt.AlignCenter)
        self.forecastIcon3.setObjectName("forecastIcon3")
        self.gridLayout_2.addWidget(self.forecastIcon3, 1, 2, 1, 1)
        self.forecastTemp3 = QtWidgets.QLabel(self.layoutWidget_2)
        self.forecastTemp3.setText("")
        self.forecastTemp3.setObjectName("forecastTemp3")
        self.gridLayout_2.addWidget(self.forecastTemp3, 2, 2, 1, 1)
        self.forecastTemp1 = QtWidgets.QLabel(self.layoutWidget_2)
        self.forecastTemp1.setText("")
        self.forecastTemp1.setObjectName("forecastTemp1")
        self.gridLayout_2.addWidget(self.forecastTemp1, 2, 0, 1, 1)
        self.forecastTime1 = QtWidgets.QLabel(self.layoutWidget_2)
        self.forecastTime1.setAlignment(QtCore.Qt.AlignCenter)
        self.forecastTime1.setObjectName("forecastTime1")
        self.gridLayout_2.addWidget(self.forecastTime1, 0, 0, 1, 1)
        self.forecastTime2 = QtWidgets.QLabel(self.layoutWidget_2)
        self.forecastTime2.setAlignment(QtCore.Qt.AlignCenter)
        self.forecastTime2.setObjectName("forecastTime2")
        self.gridLayout_2.addWidget(self.forecastTime2, 0, 1, 1, 1)
        self.forecastTime3 = QtWidgets.QLabel(self.layoutWidget_2)
        self.forecastTime3.setAlignment(QtCore.Qt.AlignCenter)
        self.forecastTime3.setObjectName("forecastTime3")
        self.gridLayout_2.addWidget(self.forecastTime3, 0, 2, 1, 1)
        self.forecastTime4 = QtWidgets.QLabel(self.layoutWidget_2)
        self.forecastTime4.setAlignment(QtCore.Qt.AlignCenter)
        self.forecastTime4.setObjectName("forecastTime4")
        self.gridLayout_2.addWidget(self.forecastTime4, 0, 3, 1, 1)
        self.forecastTime5 = QtWidgets.QLabel(self.layoutWidget_2)
        self.forecastTime5.setAlignment(QtCore.Qt.AlignCenter)
        self.forecastTime5.setObjectName("forecastTime5")
        self.gridLayout_2.addWidget(self.forecastTime5, 0, 4, 1, 1)
        self.layoutWidget_4 = QtWidgets.QWidget(self.widget_plotRandom)
        self.layoutWidget_4.setGeometry(QtCore.QRect(0, 10, 310, 63))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget_4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.weatherIcon = QtWidgets.QLabel(self.layoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.weatherIcon.sizePolicy().hasHeightForWidth())
        self.weatherIcon.setSizePolicy(sizePolicy)
        self.weatherIcon.setMinimumSize(QtCore.QSize(16, 16))
        self.weatherIcon.setMaximumSize(QtCore.QSize(16, 16))
        self.weatherIcon.setText("")
        self.weatherIcon.setObjectName("weatherIcon")
        self.horizontalLayout_4.addWidget(self.weatherIcon)
        self.weatherLabel = QtWidgets.QLabel(self.layoutWidget_4)
        self.weatherLabel.setText("")
        self.weatherLabel.setObjectName("weatherLabel")
        self.horizontalLayout_4.addWidget(self.weatherLabel)
        self.verticalLayout_4.addWidget(self.widget_plotRandom)
        self.tabWidget_bottom_left.addTab(self.tab_2, "")
        self.gridLayout_main.addWidget(self.tabWidget_bottom_left, 2, 0, 1, 1)
        self.verticalLayout_bottom_right = QtWidgets.QVBoxLayout()
        self.verticalLayout_bottom_right.setObjectName("verticalLayout_bottom_right")
        self.gridLayout_main.addLayout(self.verticalLayout_bottom_right, 2, 1, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lineEdit_location = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_location.setObjectName("lineEdit_location")
        self.horizontalLayout_3.addWidget(self.lineEdit_location)
        self.b_update = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.b_update.setCursor(QtGui.QCursor(QtCore.Qt.BlankCursor))
        self.b_update.setObjectName("b_update")
        self.horizontalLayout_3.addWidget(self.b_update)
        self.gridLayout_main.addLayout(self.horizontalLayout_3, 3, 0, 1, 1)
        self.b_update_2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.b_update_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.b_update_2.setObjectName("b_update_2")
        self.gridLayout_main.addWidget(self.b_update_2, 3, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menuOptions = QtWidgets.QMenu(self.menubar)
        self.menuOptions.setObjectName("menuOptions")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        self.menuWindow = QtWidgets.QMenu(self.menubar)
        self.menuWindow.setObjectName("menuWindow")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionGeneral = QtWidgets.QAction(MainWindow)
        self.actionGeneral.setObjectName("actionGeneral")
        self.actionVersion_1_0 = QtWidgets.QAction(MainWindow)
        self.actionVersion_1_0.setObjectName("actionVersion_1_0")
        self.actionLanguage = QtWidgets.QAction(MainWindow)
        self.actionLanguage.setObjectName("actionLanguage")
        self.actionSize = QtWidgets.QAction(MainWindow)
        self.actionSize.setObjectName("actionSize")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.menuOptions.addAction(self.actionGeneral)
        self.menuOptions.addAction(self.actionLanguage)
        self.menuOptions.addAction(self.actionSize)
        self.menuAbout.addAction(self.actionVersion_1_0)
        self.menuWindow.addAction(self.actionQuit)
        self.menubar.addAction(self.menuOptions.menuAction())
        self.menubar.addAction(self.menuWindow.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget_bottom_left.setCurrentIndex(1)
        self.actionQuit.triggered.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "TextLabel"))
        self.label_2.setText(_translate("MainWindow", "TextLabel"))
        self.label_16.setText(_translate("MainWindow", "Barometer"))
        self.label_17.setText(_translate("MainWindow", "Temperature"))
        self.label_18.setText(_translate("MainWindow", "Humidity"))
        self.label_19.setText(_translate("MainWindow", "Pressure"))
        self.label_20.setText(_translate("MainWindow", "Location"))
        self.label_21.setText(_translate("MainWindow", "Longitude"))
        self.label_22.setText(_translate("MainWindow", "Latitude"))
        self.label_23.setText(_translate("MainWindow", "Sunrise"))
        self.label_24.setText(_translate("MainWindow", "Speed"))
        self.label_25.setText(_translate("MainWindow", "Wind"))
        self.tabWidget_bottom_left.setTabText(self.tabWidget_bottom_left.indexOf(self.tab), _translate("MainWindow", "Tab 1"))
        self.forecastTime1.setText(_translate("MainWindow", "+3h"))
        self.forecastTime2.setText(_translate("MainWindow", "+6h"))
        self.forecastTime3.setText(_translate("MainWindow", "+9h"))
        self.forecastTime4.setText(_translate("MainWindow", "+12h"))
        self.forecastTime5.setText(_translate("MainWindow", "+15h"))
        self.tabWidget_bottom_left.setTabText(self.tabWidget_bottom_left.indexOf(self.tab_2), _translate("MainWindow", "Tab 2"))
        self.lineEdit_location.setText(_translate("MainWindow", "Jönköping,Sweden"))
        self.b_update.setText(_translate("MainWindow", "Update"))
        self.b_update_2.setText(_translate("MainWindow", "update"))
        self.menuOptions.setTitle(_translate("MainWindow", "Options"))
        self.menuAbout.setTitle(_translate("MainWindow", "About"))
        self.menuWindow.setTitle(_translate("MainWindow", "Window"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionGeneral.setText(_translate("MainWindow", "General"))
        self.actionVersion_1_0.setText(_translate("MainWindow", "Version 1.0"))
        self.actionLanguage.setText(_translate("MainWindow", "Language"))
        self.actionSize.setText(_translate("MainWindow", "Size"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))

